### ISSUE TITLE
Permissions error when installing without sudo

### ISSUE THREAD

**Issue by mofahead** [kennethreitz/delegator.py#11]
Ubuntu 16.10, Python 3.5, pip3
`$ pip3 install delegator.py`
...
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/delegator.py'

I was under the impression that installing using pip with sudo is problematic and best avoided.

**Comment by JacobOscarson** [comment]
That one will be difficult to avoid since it's installing stuff into the system Python. The `sudo` necessary might actually be a good thing since it makes it explicit what happens and also gives a warning that it's the system itself that's being manipulated. An alternative solution is to make a system package installable via `apt-get`.

**Comment by nateprewitt** [comment]
@mofahead, you are correct that installing from pip with sudo is ill advised. It would seem that your current (or now previous) system configuration doesn't have correct permissions set up. You'll need to resolve this before installing.

@JacobOscarson even for a system install, I would **strongly** recommend not using sudo with pip. It may have unintended effects on ownership for packages and create more problems. The better solution is to ensure the user account used is in a sufficient group, or the python user:group permissions are configured to be appropriately permissive. Running all of your python code as root can introduce an abundance of problems.
